object fmManual: TfmManual
  Tag = 6
  Left = 230
  Top = 13
  Hint = 'Y'
  BorderStyle = bsDialog
  Caption = 'fmManual'
  ClientHeight = 816
  ClientWidth = 1083
  Color = 13430215
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = #26032#32048#26126#39636
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  WindowState = wsMaximized
  PixelsPerInch = 96
  TextHeight = 16
  object BitBtn1: TBitBtn
    Left = 256
    Top = 752
    Width = 113
    Height = 57
    TabOrder = 0
    Kind = bkOK
  end
  object PageControl1: TPageControl
    Left = 0
    Top = 0
    Width = 1457
    Height = 737
    ActivePage = TabSheet1
    TabIndex = 0
    TabOrder = 1
    object TabSheet1: TTabSheet
      Caption = '1/2'
      object SpeedButton7: TSpeedButton
        Left = 400
        Top = 617
        Width = 177
        Height = 57
        Caption = #30495#31354'off'
        OnClick = SpeedButton7Click
      end
      object GroupBox5: TGroupBox
        Left = 8
        Top = 8
        Width = 353
        Height = 681
        Caption = #21462#22522#26495'/'#38291#38548#26448' '#20301#32622#35373#23450
        TabOrder = 0
        object btnSSY: TSpeedButton
          Left = 264
          Top = 30
          Width = 41
          Height = 28
          Caption = 'GO!'
          OnClick = btnSSYClick
        end
        object SpeedButton9: TSpeedButton
          Tag = 1
          Left = 264
          Top = 62
          Width = 41
          Height = 28
          Caption = 'GO!'
          OnClick = btnSSYClick
        end
        object SpeedButton14: TSpeedButton
          Tag = 48
          Left = 16
          Top = 160
          Width = 185
          Height = 57
          Caption = #22522#26495#21560#30436'('#19978'\'#19979')'
          OnClick = SpeedButton14Click
        end
        object X48: TShape
          Left = 208
          Top = 160
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X49: TShape
          Left = 208
          Top = 200
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object SpeedButton10: TSpeedButton
          Tag = 2
          Left = 264
          Top = 94
          Width = 41
          Height = 28
          Caption = 'GO!'
          OnClick = btnSSYClick
        end
        object SpeedButton11: TSpeedButton
          Tag = 3
          Left = 264
          Top = 126
          Width = 41
          Height = 28
          Caption = 'GO!'
          OnClick = btnSSYClick
        end
        object SpeedButton32: TSpeedButton
          Tag = 50
          Left = 16
          Top = 224
          Width = 185
          Height = 57
          Hint = '54'
          Caption = #22522#26495#21560#30436'('#30495#31354')'
          OnClick = SpeedButton53Click
        end
        object X52: TShape
          Left = 207
          Top = 244
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object SpeedButton12: TSpeedButton
          Tag = 4
          Left = 264
          Top = 294
          Width = 41
          Height = 28
          Caption = 'GO!'
          OnClick = btnSSYClick
        end
        object SpeedButton54: TSpeedButton
          Tag = 49
          Left = 16
          Top = 368
          Width = 185
          Height = 57
          Caption = #38291#38548#26448#21560#30436'('#19978'\'#19979')'
          OnClick = SpeedButton14Click
        end
        object X50: TShape
          Left = 208
          Top = 368
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X51: TShape
          Left = 208
          Top = 408
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object SpeedButton13: TSpeedButton
          Tag = 5
          Left = 264
          Top = 326
          Width = 41
          Height = 28
          Caption = 'GO!'
          OnClick = btnSSYClick
        end
        object SpeedButton53: TSpeedButton
          Tag = 52
          Left = 16
          Top = 440
          Width = 185
          Height = 57
          Hint = '55'
          Caption = #38291#38548#26448#21560#30436'('#30495#31354')'
          OnClick = SpeedButton53Click
        end
        object X53: TShape
          Left = 208
          Top = 463
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object SpeedButton1: TSpeedButton
          Left = 16
          Top = 520
          Width = 169
          Height = 65
          Caption = #22522#26495#26009#20489#33267#28310#20633#20301#32622
          OnClick = SpeedButton1Click
        end
        object X32: TShape
          Left = 192
          Top = 520
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X38: TShape
          Left = 192
          Top = 544
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X33: TShape
          Left = 192
          Top = 640
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object SpeedButton2: TSpeedButton
          Left = 16
          Top = 592
          Width = 169
          Height = 65
          Caption = #22522#26495#26009#20489#33267#19979#20301
          OnClick = SpeedButton2Click
        end
        object Label1: TLabel
          Left = 232
          Top = 160
          Width = 27
          Height = 16
          Caption = 'X48'
        end
        object Label2: TLabel
          Left = 232
          Top = 200
          Width = 27
          Height = 16
          Caption = 'X49'
        end
        object Label3: TLabel
          Left = 232
          Top = 243
          Width = 27
          Height = 16
          Caption = 'X52'
        end
        object Label4: TLabel
          Left = 232
          Top = 368
          Width = 27
          Height = 16
          Caption = 'X50'
        end
        object Label5: TLabel
          Left = 232
          Top = 408
          Width = 27
          Height = 16
          Caption = 'X51'
        end
        object Label6: TLabel
          Left = 232
          Top = 464
          Width = 27
          Height = 16
          Caption = 'X53'
        end
        object Label7: TLabel
          Left = 216
          Top = 520
          Width = 27
          Height = 16
          Caption = 'X32'
        end
        object Label8: TLabel
          Left = 216
          Top = 544
          Width = 27
          Height = 16
          Caption = 'X38'
        end
        object Label9: TLabel
          Left = 216
          Top = 640
          Width = 27
          Height = 16
          Caption = 'X33'
        end
        object StaticText1: TStaticText
          Tag = 6
          Left = 16
          Top = 30
          Width = 113
          Height = 28
          Hint = 'm_dSSPickerPickPos'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21462#22522#26495#20301#32622'('#26799')'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 0
          OnClick = StaticText1Click
        end
        object m_dSSPickerPickPos: TEdit
          Left = 136
          Top = 30
          Width = 81
          Height = 24
          TabOrder = 1
          Text = 'm_dSSPickerPickPos'
        end
        object StaticText2: TStaticText
          Left = 224
          Top = 30
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 2
        end
        object StaticText4: TStaticText
          Tag = 6
          Left = 16
          Top = 62
          Width = 113
          Height = 28
          Hint = 'm_dSSPickerPickRailPos'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21462#22522#26495#20301#32622'('#36556')'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 3
          OnClick = StaticText1Click
        end
        object m_dSSPickerPickRailPos: TEdit
          Left = 136
          Top = 62
          Width = 81
          Height = 24
          TabOrder = 4
          Text = 'editPickSpacerPosY'
        end
        object StaticText6: TStaticText
          Left = 224
          Top = 62
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 5
        end
        object StaticText9: TStaticText
          Tag = 6
          Left = 16
          Top = 94
          Width = 113
          Height = 28
          Hint = 'm_dSSPickerPutPos0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #25918#22522#26495#20301#32622'('#24460')'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 6
          OnClick = StaticText1Click
        end
        object m_dSSPickerPutPos0: TEdit
          Left = 136
          Top = 94
          Width = 81
          Height = 24
          TabOrder = 7
          Text = 'editPickSpacerPosY'
        end
        object StaticText10: TStaticText
          Left = 224
          Top = 94
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 8
        end
        object StaticText21: TStaticText
          Tag = 6
          Left = 16
          Top = 294
          Width = 113
          Height = 28
          Hint = 'm_dSpaPickerPickPos'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21462#38291#38548#26448#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 9
          OnClick = StaticText1Click
        end
        object m_dSpaPickerPickPos: TEdit
          Left = 136
          Top = 294
          Width = 81
          Height = 24
          TabOrder = 10
          Text = 'editPickSpacerPosY'
        end
        object StaticText22: TStaticText
          Left = 224
          Top = 294
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 11
        end
        object StaticText23: TStaticText
          Left = 224
          Top = 326
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 12
        end
        object m_dSpaPickerThrowPos: TEdit
          Left = 136
          Top = 326
          Width = 81
          Height = 24
          TabOrder = 13
          Text = 'editPickSpacerPosY'
        end
        object StaticText24: TStaticText
          Tag = 6
          Left = 16
          Top = 326
          Width = 113
          Height = 28
          Hint = 'm_dSpaPickerThrowPos'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #19999#38291#38548#26448#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 14
          OnClick = StaticText1Click
        end
        object StaticText25: TStaticText
          Tag = 6
          Left = 16
          Top = 126
          Width = 113
          Height = 28
          Hint = 'm_dSSPickerPutPos1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #25918#22522#26495#20301#32622'('#21069')'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 15
          OnClick = StaticText1Click
        end
        object m_dSSPickerPutPos1: TEdit
          Left = 136
          Top = 126
          Width = 81
          Height = 24
          TabOrder = 16
          Text = 'editPickSpacerPosY'
        end
        object StaticText26: TStaticText
          Left = 224
          Top = 126
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 17
        end
      end
      object GroupBox8: TGroupBox
        Left = 384
        Top = 8
        Width = 673
        Height = 177
        Caption = #21462#22522#26495' '#20301#32622#35373#23450
        TabOrder = 1
        object SpeedButton34: TSpeedButton
          Tag = 2
          Left = 272
          Top = 38
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnSCYClick
        end
        object SpeedButton42: TSpeedButton
          Tag = 4
          Left = 592
          Top = 38
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnSCYClick
        end
        object SpeedButton60: TSpeedButton
          Tag = 16
          Left = 24
          Top = 96
          Width = 137
          Height = 57
          Caption = #22522#26495#21560#30436'('#19978'\'#19979')'
          OnClick = SpeedButton14Click
        end
        object SpeedButton61: TSpeedButton
          Tag = 18
          Left = 344
          Top = 96
          Width = 137
          Height = 57
          Hint = '22'
          Caption = #22522#26495#21560#30436'('#30495#31354')'
          OnClick = SpeedButton53Click
        end
        object X16: TShape
          Left = 168
          Top = 96
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X17: TShape
          Left = 168
          Top = 136
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X20: TShape
          Left = 488
          Top = 120
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object Label10: TLabel
          Left = 192
          Top = 96
          Width = 27
          Height = 16
          Caption = 'X16'
        end
        object Label11: TLabel
          Left = 192
          Top = 136
          Width = 27
          Height = 16
          Caption = 'X17'
        end
        object Label18: TLabel
          Left = 512
          Top = 120
          Width = 27
          Height = 16
          Caption = 'X20'
        end
        object StaticText78: TStaticText
          Tag = 7
          Left = 24
          Top = 38
          Width = 122
          Height = 28
          Hint = 'm_dSCPickerPickSSPosY1'
          Alignment = taRightJustify
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21069#21462#22522#26495#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 0
          OnClick = StaticText1Click
        end
        object m_dSCPickerPickSSPosY1: TEdit
          Left = 152
          Top = 38
          Width = 81
          Height = 24
          TabOrder = 1
          Text = 'editPickSpacerPosY'
        end
        object StaticText80: TStaticText
          Left = 240
          Top = 38
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 2
        end
        object StaticText74: TStaticText
          Tag = 7
          Left = 344
          Top = 38
          Width = 122
          Height = 28
          Hint = 'm_dSCPickerPickSSPosY0'
          Alignment = taRightJustify
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #24460#21462#22522#26495#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 3
          OnClick = StaticText1Click
        end
        object m_dSCPickerPickSSPosY0: TEdit
          Left = 472
          Top = 38
          Width = 81
          Height = 24
          TabOrder = 4
          Text = 'editPickSpacerPosY'
        end
        object StaticText76: TStaticText
          Left = 560
          Top = 38
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 5
        end
      end
      object GroupBox14: TGroupBox
        Left = 384
        Top = 312
        Width = 673
        Height = 97
        Caption = #25918#22522#26495' '#20301#32622#35373#23450
        TabOrder = 2
        object SpeedButton5: TSpeedButton
          Tag = 16
          Left = 272
          Top = 38
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnSCYClick
        end
        object SpeedButton6: TSpeedButton
          Tag = 17
          Left = 592
          Top = 38
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnSCYClick
        end
        object StaticText100: TStaticText
          Tag = 7
          Left = 344
          Top = 38
          Width = 122
          Height = 28
          Hint = 'm_editSBTNGBoxPos'
          Alignment = taRightJustify
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #19999#26820#22522#26495#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 0
          OnClick = StaticText1Click
        end
        object m_editSBTNGBoxPos: TEdit
          Left = 472
          Top = 38
          Width = 81
          Height = 24
          TabOrder = 1
          Text = 'editPickSpacerPosY'
        end
        object StaticText102: TStaticText
          Left = 560
          Top = 38
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 2
        end
        object StaticText104: TStaticText
          Tag = 7
          Left = 24
          Top = 38
          Width = 122
          Height = 28
          Hint = 'm_editSCPickerPutSSPos'
          Alignment = taRightJustify
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #27969#36947#22522#26495#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 3
          OnClick = StaticText1Click
        end
        object m_editSCPickerPutSSPos: TEdit
          Left = 152
          Top = 38
          Width = 81
          Height = 24
          TabOrder = 4
          Text = 'editPickSpacerPosY'
        end
        object StaticText106: TStaticText
          Left = 240
          Top = 38
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 5
        end
      end
      object GroupBox13: TGroupBox
        Left = 384
        Top = 200
        Width = 673
        Height = 97
        Caption = #27298#26597'2D Code'#20301#32622#35373#23450
        TabOrder = 3
        object SpeedButton3: TSpeedButton
          Tag = 14
          Left = 272
          Top = 38
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnSCYClick
        end
        object SpeedButton4: TSpeedButton
          Tag = 15
          Left = 592
          Top = 38
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnSCYClick
        end
        object StaticText95: TStaticText
          Tag = 7
          Left = 344
          Top = 38
          Width = 122
          Height = 28
          Hint = 'm_editLaserCodeReaderPos1'
          Alignment = taRightJustify
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #19979#20596#22522#26495#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 0
          OnClick = StaticText1Click
        end
        object m_editLaserCodeReaderPos1: TEdit
          Left = 472
          Top = 38
          Width = 81
          Height = 24
          TabOrder = 1
          Text = 'editPickSpacerPosY'
        end
        object StaticText96: TStaticText
          Left = 560
          Top = 38
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 2
        end
        object StaticText97: TStaticText
          Tag = 7
          Left = 24
          Top = 38
          Width = 122
          Height = 28
          Hint = 'm_editLaserCodeReaderPos0'
          Alignment = taRightJustify
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #19978#20596#22522#26495#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 3
          OnClick = StaticText1Click
        end
        object m_editLaserCodeReaderPos0: TEdit
          Left = 152
          Top = 38
          Width = 81
          Height = 24
          TabOrder = 4
          Text = 'editPickSpacerPosY'
        end
        object StaticText98: TStaticText
          Left = 240
          Top = 38
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 5
        end
      end
    end
    object TabSheet2: TTabSheet
      Caption = '2/2'
      ImageIndex = 1
      object GroupBox1: TGroupBox
        Left = 16
        Top = 353
        Width = 657
        Height = 328
        Caption = #31227#21205#36617#21488'('#21069')'
        TabOrder = 0
        object btnFTX: TSpeedButton
          Left = 264
          Top = 30
          Width = 41
          Height = 28
          Hint = 'X'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton15: TSpeedButton
          Tag = 1
          Left = 264
          Top = 62
          Width = 41
          Height = 28
          Hint = 'X'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton16: TSpeedButton
          Tag = 2
          Left = 264
          Top = 94
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton22: TSpeedButton
          Tag = 8
          Left = 584
          Top = 30
          Width = 41
          Height = 28
          Hint = 'X'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton17: TSpeedButton
          Tag = 3
          Left = 584
          Top = 62
          Width = 41
          Height = 28
          Hint = 'X'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton18: TSpeedButton
          Tag = 4
          Left = 584
          Top = 94
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton21: TSpeedButton
          Tag = 6
          Left = 904
          Top = 30
          Width = 41
          Height = 28
          Hint = 'X'
          Caption = 'GO!'
          Visible = False
          OnClick = btnFTXClick
        end
        object SpeedButton20: TSpeedButton
          Tag = 7
          Left = 904
          Top = 62
          Width = 41
          Height = 28
          Hint = 'Y2'
          Caption = 'GO!'
          Visible = False
          OnClick = btnFTXClick
        end
        object SpeedButton19: TSpeedButton
          Tag = 5
          Left = 264
          Top = 126
          Width = 41
          Height = 28
          Hint = 'X'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton57: TSpeedButton
          Tag = 1
          Left = 24
          Top = 208
          Width = 137
          Height = 57
          Caption = #24179#21488#30495#31354
          OnClick = SpeedButton14Click
        end
        object SpeedButton56: TSpeedButton
          Tag = 3
          Left = 208
          Top = 208
          Width = 137
          Height = 57
          Caption = #24179#21488#38752#37002
          OnClick = SpeedButton14Click
        end
        object X2: TShape
          Left = 24
          Top = 273
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object Label20: TLabel
          Left = 48
          Top = 273
          Width = 19
          Height = 16
          Caption = 'X2'
        end
        object SpeedButton8: TSpeedButton
          Tag = 4
          Left = 208
          Top = 264
          Width = 137
          Height = 57
          Caption = #24179#21488#38752#37002'2'
          OnClick = SpeedButton14Click
        end
        object SpeedButton35: TSpeedButton
          Left = 411
          Top = 208
          Width = 137
          Height = 57
          Caption = #24179#21488#32763#36681
          OnClick = SpeedButton14Click
        end
        object SpeedButton37: TSpeedButton
          Tag = 2
          Left = 411
          Top = 264
          Width = 137
          Height = 57
          Caption = #32763#36681#37782#23450
          OnClick = SpeedButton14Click
        end
        object X5: TShape
          Left = 352
          Top = 231
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X0: TShape
          Left = 560
          Top = 217
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X3: TShape
          Left = 560
          Top = 273
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X6: TShape
          Left = 352
          Top = 281
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X1: TShape
          Left = 560
          Top = 241
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X4: TShape
          Left = 560
          Top = 297
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object Label14: TLabel
          Left = 376
          Top = 231
          Width = 19
          Height = 16
          Caption = 'X5'
        end
        object Label15: TLabel
          Left = 376
          Top = 281
          Width = 19
          Height = 16
          Caption = 'X6'
        end
        object Label16: TLabel
          Left = 584
          Top = 217
          Width = 45
          Height = 16
          Caption = 'X0('#27491')'
        end
        object Label17: TLabel
          Left = 584
          Top = 241
          Width = 45
          Height = 16
          Caption = 'X1('#21453')'
        end
        object Label19: TLabel
          Left = 584
          Top = 273
          Width = 38
          Height = 16
          Caption = 'X3(L)'
        end
        object Label22: TLabel
          Left = 584
          Top = 297
          Width = 40
          Height = 16
          Caption = 'X4(U)'
        end
        object SpeedButton39: TSpeedButton
          Tag = 18
          Left = 584
          Top = 62
          Width = 41
          Height = 28
          Hint = 'X'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton40: TSpeedButton
          Tag = 19
          Left = 584
          Top = 94
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton46: TSpeedButton
          Tag = 22
          Left = 584
          Top = 126
          Width = 41
          Height = 28
          Hint = 'X'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton47: TSpeedButton
          Tag = 23
          Left = 584
          Top = 158
          Width = 41
          Height = 28
          Hint = 'X'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object StaticText13: TStaticText
          Tag = 4
          Left = 16
          Top = 30
          Width = 122
          Height = 28
          Hint = 'm_dTablePutDownPos1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #25509#22522#26495#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 0
          OnClick = StaticText1Click
        end
        object m_dTablePutDownPos1: TEdit
          Left = 144
          Top = 30
          Width = 81
          Height = 24
          TabOrder = 1
          Text = 'editPickSpacerPosY'
        end
        object StaticText15: TStaticText
          Left = 232
          Top = 30
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 2
        end
        object StaticText17: TStaticText
          Tag = 4
          Left = 16
          Top = 62
          Width = 122
          Height = 28
          Hint = 'm_dTableMarkPosX1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38651#30524#23450#20301#20301#32622'(X)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 3
          OnClick = StaticText1Click
        end
        object m_dTableMarkPosX1: TEdit
          Left = 144
          Top = 62
          Width = 81
          Height = 24
          TabOrder = 4
          Text = 'editPickSpacerPosY'
        end
        object StaticText19: TStaticText
          Left = 232
          Top = 62
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 5
        end
        object StaticText20: TStaticText
          Tag = 8
          Left = 16
          Top = 94
          Width = 122
          Height = 28
          Hint = 'm_dTableMarkPosY1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38651#30524#23450#20301#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 6
          OnClick = StaticText1Click
        end
        object m_dTableMarkPosY1: TEdit
          Left = 144
          Top = 94
          Width = 81
          Height = 24
          TabOrder = 7
          Text = 'editPickSpacerPosY1'
        end
        object StaticText27: TStaticText
          Left = 232
          Top = 94
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 8
        end
        object StaticText28: TStaticText
          Tag = 4
          Left = 320
          Top = 62
          Width = 122
          Height = 28
          Hint = 'm_dTableVenderCodePosX1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = '2D Code'#20301#32622'(X)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 9
          OnClick = StaticText1Click
        end
        object StaticText29: TStaticText
          Tag = 8
          Left = 320
          Top = 94
          Width = 122
          Height = 28
          Hint = 'm_dTableVenderCodePosY1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = '2D Code'#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 10
          OnClick = StaticText1Click
        end
        object m_dTableVenderCodePosX1: TEdit
          Left = 456
          Top = 62
          Width = 81
          Height = 24
          TabOrder = 11
          Text = 'editPickSpacerPosY'
        end
        object m_dTableVenderCodePosY1: TEdit
          Left = 456
          Top = 94
          Width = 81
          Height = 24
          TabOrder = 12
          Text = 'editPickSpacerPosY'
        end
        object StaticText30: TStaticText
          Left = 544
          Top = 62
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 13
        end
        object StaticText31: TStaticText
          Left = 544
          Top = 94
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 14
        end
        object StaticText32: TStaticText
          Tag = 4
          Left = 16
          Top = 126
          Width = 122
          Height = 28
          Hint = 'm_dTableLaserPos1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38647#23556#21051#21360#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 15
          OnClick = StaticText1Click
        end
        object m_dTableLaserPos1: TEdit
          Left = 144
          Top = 126
          Width = 81
          Height = 24
          TabOrder = 16
          Text = 'editPickSpacerPosY'
        end
        object StaticText33: TStaticText
          Left = 232
          Top = 126
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 17
        end
        object StaticText34: TStaticText
          Tag = 4
          Left = 640
          Top = 30
          Width = 129
          Height = 28
          Hint = 'm_dTableLaserCodePosX1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21051#21360#27298#26597#20301#32622'(X)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 18
          Visible = False
          OnClick = StaticText1Click
        end
        object StaticText35: TStaticText
          Tag = 5
          Left = 640
          Top = 62
          Width = 129
          Height = 28
          Hint = 'm_dTableLaserCodePosY1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21051#21360#27298#26597#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 19
          Visible = False
          OnClick = StaticText1Click
        end
        object m_dTableLaserCodePosX1: TEdit
          Left = 776
          Top = 30
          Width = 81
          Height = 24
          TabOrder = 20
          Text = 'editPickSpacerPosY'
          Visible = False
        end
        object m_dTableLaserCodePosY1: TEdit
          Left = 776
          Top = 62
          Width = 81
          Height = 24
          TabOrder = 21
          Text = 'editPickSpacerPosY'
          Visible = False
        end
        object StaticText36: TStaticText
          Left = 864
          Top = 30
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 22
          Visible = False
        end
        object StaticText40: TStaticText
          Left = 864
          Top = 62
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 23
          Visible = False
        end
        object StaticText41: TStaticText
          Tag = 4
          Left = 320
          Top = 30
          Width = 129
          Height = 28
          Hint = 'm_dTablePickUpPos1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21462#22522#26495#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 24
          OnClick = StaticText1Click
        end
        object m_dTablePickUpPos1: TEdit
          Left = 456
          Top = 30
          Width = 81
          Height = 24
          TabOrder = 25
          Text = 'editPickSpacerPosY'
        end
        object StaticText42: TStaticText
          Left = 544
          Top = 30
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 26
        end
        object StaticText3: TStaticText
          Tag = 4
          Left = 320
          Top = 62
          Width = 129
          Height = 28
          Hint = 'm_dTableMarkPos2X1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38651#30524#23450#20301#20301#32622'2(X)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 27
          OnClick = StaticText1Click
        end
        object m_dTableMarkPos2X1: TEdit
          Left = 456
          Top = 62
          Width = 81
          Height = 24
          TabOrder = 28
          Text = 'editPickSpacerPosY'
        end
        object StaticText5: TStaticText
          Left = 544
          Top = 62
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 29
        end
        object StaticText7: TStaticText
          Tag = 8
          Left = 320
          Top = 94
          Width = 129
          Height = 28
          Hint = 'm_dTableMarkPos2Y1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38651#30524#23450#20301#20301#32622'2(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 30
          OnClick = StaticText1Click
        end
        object m_dTableMarkPos2Y1: TEdit
          Left = 456
          Top = 94
          Width = 81
          Height = 24
          TabOrder = 31
          Text = 'editPickSpacerPosY1'
        end
        object StaticText8: TStaticText
          Left = 544
          Top = 94
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 32
        end
        object StaticText116: TStaticText
          Tag = 4
          Left = 320
          Top = 126
          Width = 129
          Height = 28
          Hint = 'm_dTableBackSpeedDown1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #22238#31243#28187#36895#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 33
          OnClick = StaticText1Click
        end
        object m_dTableBackSpeedDown1: TEdit
          Left = 456
          Top = 126
          Width = 81
          Height = 24
          TabOrder = 34
          Text = 'editPickSpacerPosY'
        end
        object StaticText117: TStaticText
          Left = 544
          Top = 126
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 35
        end
        object StaticText118: TStaticText
          Tag = 4
          Left = 320
          Top = 158
          Width = 129
          Height = 28
          Hint = 'm_dTableBackSpeedUp1'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #22238#31243#21152#36895#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 36
          OnClick = StaticText1Click
        end
        object m_dTableBackSpeedUp1: TEdit
          Left = 456
          Top = 158
          Width = 81
          Height = 24
          TabOrder = 37
          Text = 'editPickSpacerPosY'
        end
        object StaticText119: TStaticText
          Left = 544
          Top = 158
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 38
        end
      end
      object GroupBox7: TGroupBox
        Left = 16
        Top = 17
        Width = 657
        Height = 328
        Caption = #31227#21205#36617#21488'('#24460')'
        TabOrder = 1
        object SpeedButton23: TSpeedButton
          Tag = 9
          Left = 264
          Top = 30
          Width = 41
          Height = 28
          Hint = 'X1'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton24: TSpeedButton
          Tag = 10
          Left = 264
          Top = 62
          Width = 41
          Height = 28
          Hint = 'X1'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton25: TSpeedButton
          Tag = 11
          Left = 264
          Top = 94
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton28: TSpeedButton
          Tag = 14
          Left = 264
          Top = 126
          Width = 41
          Height = 28
          Hint = 'X1'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton31: TSpeedButton
          Tag = 17
          Left = 584
          Top = 30
          Width = 41
          Height = 28
          Hint = 'X1'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton26: TSpeedButton
          Tag = 12
          Left = 584
          Top = 62
          Width = 41
          Height = 28
          Hint = 'X1'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton30: TSpeedButton
          Tag = 15
          Left = 904
          Top = 30
          Width = 41
          Height = 28
          Hint = 'X1'
          Caption = 'GO!'
          Visible = False
          OnClick = btnFTXClick
        end
        object SpeedButton29: TSpeedButton
          Tag = 16
          Left = 904
          Top = 62
          Width = 41
          Height = 28
          Hint = 'Y2'
          Caption = 'GO!'
          Visible = False
          OnClick = btnFTXClick
        end
        object SpeedButton27: TSpeedButton
          Tag = 13
          Left = 584
          Top = 94
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton59: TSpeedButton
          Tag = 9
          Left = 24
          Top = 208
          Width = 137
          Height = 57
          Caption = #24179#21488#30495#31354
          OnClick = SpeedButton14Click
        end
        object X10: TShape
          Left = 27
          Top = 276
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object Label21: TLabel
          Left = 52
          Top = 278
          Width = 27
          Height = 16
          Caption = 'X10'
        end
        object SpeedButton58: TSpeedButton
          Tag = 11
          Left = 210
          Top = 208
          Width = 137
          Height = 57
          Caption = #24179#21488#38752#37002
          OnClick = SpeedButton14Click
        end
        object SpeedButton33: TSpeedButton
          Tag = 12
          Left = 210
          Top = 264
          Width = 137
          Height = 57
          Caption = #24179#21488#38752#37002'2'
          OnClick = SpeedButton14Click
        end
        object SpeedButton36: TSpeedButton
          Tag = 8
          Left = 413
          Top = 208
          Width = 137
          Height = 57
          Caption = #24179#21488#32763#36681
          OnClick = SpeedButton14Click
        end
        object SpeedButton38: TSpeedButton
          Tag = 10
          Left = 413
          Top = 264
          Width = 137
          Height = 57
          Caption = #32763#36681#37782#23450
          OnClick = SpeedButton14Click
        end
        object X13: TShape
          Left = 354
          Top = 233
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X14: TShape
          Left = 354
          Top = 289
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object Label25: TLabel
          Left = 378
          Top = 233
          Width = 27
          Height = 16
          Caption = 'X13'
        end
        object Label26: TLabel
          Left = 378
          Top = 289
          Width = 27
          Height = 16
          Caption = 'X14'
        end
        object X8: TShape
          Left = 562
          Top = 217
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X11: TShape
          Left = 562
          Top = 273
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object Label27: TLabel
          Left = 586
          Top = 217
          Width = 45
          Height = 16
          Caption = 'X8('#27491')'
        end
        object Label28: TLabel
          Left = 586
          Top = 241
          Width = 45
          Height = 16
          Caption = 'X9('#21453')'
        end
        object X9: TShape
          Left = 562
          Top = 241
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object X12: TShape
          Left = 562
          Top = 297
          Width = 17
          Height = 17
          Shape = stCircle
        end
        object Label29: TLabel
          Left = 586
          Top = 273
          Width = 46
          Height = 16
          Caption = 'X11(L)'
        end
        object Label30: TLabel
          Left = 586
          Top = 297
          Width = 48
          Height = 16
          Caption = 'X12(U)'
        end
        object SpeedButton41: TSpeedButton
          Tag = 20
          Left = 584
          Top = 62
          Width = 41
          Height = 28
          Hint = 'X1'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton43: TSpeedButton
          Tag = 21
          Left = 584
          Top = 94
          Width = 41
          Height = 28
          Hint = 'Y'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton44: TSpeedButton
          Tag = 24
          Left = 584
          Top = 126
          Width = 41
          Height = 28
          Hint = 'X1'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object SpeedButton45: TSpeedButton
          Tag = 25
          Left = 584
          Top = 158
          Width = 41
          Height = 28
          Hint = 'X1'
          Caption = 'GO!'
          OnClick = btnFTXClick
        end
        object StaticText43: TStaticText
          Tag = 5
          Left = 16
          Top = 30
          Width = 122
          Height = 28
          Hint = 'm_dTablePutDownPos0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #25509#22522#26495#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 0
          OnClick = StaticText1Click
        end
        object m_dTablePutDownPos0: TEdit
          Left = 144
          Top = 30
          Width = 81
          Height = 24
          TabOrder = 1
          Text = 'editPickSpacerPosY'
        end
        object StaticText44: TStaticText
          Left = 232
          Top = 30
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 2
        end
        object StaticText45: TStaticText
          Tag = 5
          Left = 16
          Top = 62
          Width = 122
          Height = 28
          Hint = 'm_dTableMarkPosX0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38651#30524#23450#20301#20301#32622'(X)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 3
          OnClick = StaticText1Click
        end
        object m_dTableMarkPosX0: TEdit
          Left = 144
          Top = 62
          Width = 81
          Height = 24
          TabOrder = 4
          Text = 'editPickSpacerPosY'
        end
        object StaticText46: TStaticText
          Left = 232
          Top = 62
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 5
        end
        object StaticText47: TStaticText
          Tag = 8
          Left = 16
          Top = 94
          Width = 122
          Height = 28
          Hint = 'm_dTableMarkPosY0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38651#30524#23450#20301#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 6
          OnClick = StaticText1Click
        end
        object m_dTableMarkPosY0: TEdit
          Left = 144
          Top = 94
          Width = 81
          Height = 24
          TabOrder = 7
          Text = 'editPickSpacerPosY'
        end
        object StaticText48: TStaticText
          Left = 232
          Top = 94
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 8
        end
        object StaticText49: TStaticText
          Tag = 5
          Left = 320
          Top = 62
          Width = 122
          Height = 28
          Hint = 'm_dTableVenderCodePosX0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = '2D Code'#20301#32622'(X)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 9
          OnClick = StaticText1Click
        end
        object StaticText59: TStaticText
          Tag = 8
          Left = 320
          Top = 94
          Width = 122
          Height = 28
          Hint = 'm_dTableVenderCodePosY0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = '2D Code'#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 10
          OnClick = StaticText1Click
        end
        object m_dTableVenderCodePosX0: TEdit
          Left = 456
          Top = 62
          Width = 81
          Height = 24
          TabOrder = 11
          Text = 'editPickSpacerPosY'
        end
        object m_dTableVenderCodePosY0: TEdit
          Left = 456
          Top = 94
          Width = 81
          Height = 24
          TabOrder = 12
          Text = 'editPickSpacerPosY'
        end
        object StaticText60: TStaticText
          Left = 544
          Top = 62
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 13
        end
        object StaticText61: TStaticText
          Left = 544
          Top = 94
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 14
        end
        object StaticText62: TStaticText
          Tag = 5
          Left = 16
          Top = 126
          Width = 122
          Height = 28
          Hint = 'm_dTableLaserPos0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38647#23556#21051#21360#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 15
          OnClick = StaticText1Click
        end
        object m_dTableLaserPos0: TEdit
          Left = 144
          Top = 126
          Width = 81
          Height = 24
          TabOrder = 16
          Text = 'editPickSpacerPosY'
        end
        object StaticText63: TStaticText
          Left = 232
          Top = 126
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 17
        end
        object StaticText64: TStaticText
          Tag = 8
          Left = 640
          Top = 30
          Width = 129
          Height = 28
          Hint = 'm_dTableLaserCodePosX0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21051#21360#27298#26597#20301#32622'(X)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 18
          Visible = False
          OnClick = StaticText1Click
        end
        object StaticText65: TStaticText
          Tag = 5
          Left = 640
          Top = 62
          Width = 129
          Height = 28
          Hint = 'm_dTableLaserCodePosY0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21051#21360#27298#26597#20301#32622'(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 19
          Visible = False
          OnClick = StaticText1Click
        end
        object m_dTableLaserCodePosX0: TEdit
          Left = 776
          Top = 30
          Width = 81
          Height = 24
          TabOrder = 20
          Text = 'editPickSpacerPosY'
          Visible = False
        end
        object m_dTableLaserCodePosY0: TEdit
          Left = 776
          Top = 62
          Width = 81
          Height = 24
          TabOrder = 21
          Text = 'editPickSpacerPosY'
          Visible = False
        end
        object StaticText66: TStaticText
          Left = 864
          Top = 30
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 22
          Visible = False
        end
        object StaticText67: TStaticText
          Left = 864
          Top = 62
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 23
          Visible = False
        end
        object StaticText68: TStaticText
          Tag = 5
          Left = 320
          Top = 30
          Width = 129
          Height = 28
          Hint = 'm_dTablePickUpPos0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #21462#22522#26495#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 24
          OnClick = StaticText1Click
        end
        object m_dTablePickUpPos0: TEdit
          Left = 456
          Top = 30
          Width = 81
          Height = 24
          TabOrder = 25
          Text = 'editPickSpacerPosY'
        end
        object StaticText69: TStaticText
          Left = 544
          Top = 30
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 26
        end
        object StaticText11: TStaticText
          Tag = 5
          Left = 320
          Top = 62
          Width = 129
          Height = 28
          Hint = 'm_dTableMarkPosX0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38651#30524#23450#20301#20301#32622'2(X)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 27
          OnClick = StaticText1Click
        end
        object StaticText12: TStaticText
          Tag = 8
          Left = 320
          Top = 94
          Width = 129
          Height = 28
          Hint = 'm_dTableMarkPosY0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #38651#30524#23450#20301#20301#32622'2(Y)'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 28
          OnClick = StaticText1Click
        end
        object m_dTableMarkPos2X0: TEdit
          Left = 456
          Top = 62
          Width = 81
          Height = 24
          TabOrder = 29
          Text = 'editPickSpacerPosY'
        end
        object m_dTableMarkPos2Y0: TEdit
          Left = 456
          Top = 94
          Width = 81
          Height = 24
          TabOrder = 30
          Text = 'editPickSpacerPosY'
        end
        object StaticText14: TStaticText
          Left = 544
          Top = 62
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 31
        end
        object StaticText16: TStaticText
          Left = 544
          Top = 94
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 32
        end
        object StaticText120: TStaticText
          Tag = 5
          Left = 320
          Top = 126
          Width = 129
          Height = 28
          Hint = 'm_dTableBackSpeedDown0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #22238#31243#28187#36895#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 33
          OnClick = StaticText1Click
        end
        object m_dTableBackSpeedDown0: TEdit
          Left = 456
          Top = 126
          Width = 81
          Height = 24
          TabOrder = 34
          Text = 'editPickSpacerPosY'
        end
        object StaticText121: TStaticText
          Left = 544
          Top = 126
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 35
        end
        object StaticText122: TStaticText
          Tag = 5
          Left = 320
          Top = 158
          Width = 129
          Height = 28
          Hint = 'm_dTableBackSpeedUp0'
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = #22238#31243#21152#36895#20301#32622
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 36
          OnClick = StaticText1Click
        end
        object m_dTableBackSpeedUp0: TEdit
          Left = 456
          Top = 158
          Width = 81
          Height = 24
          TabOrder = 37
          Text = 'editPickSpacerPosY'
        end
        object StaticText123: TStaticText
          Left = 544
          Top = 158
          Width = 30
          Height = 28
          AutoSize = False
          BevelInner = bvSpace
          BevelKind = bkSoft
          BevelOuter = bvNone
          BorderStyle = sbsSingle
          Caption = 'mm'
          Color = clSkyBlue
          ParentColor = False
          TabOrder = 38
        end
      end
    end
  end
  object BitBtn2: TBitBtn
    Left = 680
    Top = 751
    Width = 113
    Height = 57
    TabOrder = 2
    Kind = bkCancel
  end
  object Timer1: TTimer
    Interval = 50
    OnTimer = Timer1Timer
    Left = 1128
    Top = 720
  end
end
